version: '3'

services:
    # frontend:
    #     image: rodesc/clery-frontend:latest
    #     ports: ['80:3000']
    #     restart: always
    #     environment:
    #         GATEWAY_URL: 'http://clery.francecentral.cloudapp.azure.com:3000'

    # gateway microservice
    gateway:
        image: rodesc/clery-gateway:latest
        ports: ['3000:80']
        restart: always
        environment:
            JWT_KEY: 1284f18a8a027173483a1cd563db5c51

    ########################## Users #############################
    # users-viewer:
    #     image: phpmyadmin/phpmyadmin
    #     environment: ['PMA_ARBITRARY=1', 'PMA_HOST=users-db']
    #     restart: always
    #     ports: ['8080:80']
    #     volumes: ['/sessions']
    #     depends_on: ['users-db']

    # database of users
    users-db:
        image: mariadb
        restart: always
        ports: ['3002:5984']
        environment:
            MYSQL_ROOT_PASSWORD: clerypassword
            MYSQL_DATABASE: clery-users
        volumes: [
                './tmp/user-data:/var/lib/mysql', # database data storage on host
                './users/db-config:/docker-entrypoint-initdb.d', # database init file
            ]

    # users microservice
    users:
        image: rodesc/clery-users:latest
        depends_on: ['users-db']
        ports: ['3001:80']
        restart: always
        environment:
            DB_HOST: users-db
            DB_NAME: clery-users
            DB_USER: root
            DB_PASSWORD: clerypassword
            JWT_KEY: 1284f18a8a027173483a1cd563db5c51

    ########################## Documents #############################
    # documents microservice
    documents:
        image: rodesc/clery-documents:latest
        depends_on: ['documents-db']
        ports: ['3003:80']
        restart: always
        environment:
            DB_HOST: documents-db
            DB_NAME: documents
            DB_PORT: 3006
            DB_USER: root
            DB_PASSWORD: clerypassword

    # file-viewer:
    #     image: mongo-express
    #     restart: always
    #     ports: ['8081:8081']
    #     depends_on: ['documents-db']
    #     environment:
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: clerypassword
    #         ME_CONFIG_MONGODB_SERVER: documents-db
    #         ME_CONFIG_MONGODB_PORT: 3006

    # file database
    documents-db:
        image: mongo:3
        command: mongod --port 3006
        restart: always
        volumes:
            [
                './tmp/documents-data:/data/db',
                './documents/init-db.js:/docker-entrypoint-initdb.d/init-mongo.js',
            ]
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: clerypassword
            MONGO_INITDB_DATABASE: documents

    ########################## Analysis #############################
    # analysis microservice
    analysis:
        image: rodesc/clery-analysis:latest
        depends_on: ['legal-db']
        ports: ['3004:80']
        restart: always
        environment:
            OPENAI_API_KEY: sk-JpNsZ5FwvdlYP4QvkTP4ujR1d8F3izWH1J7Kl985
            DEEPL_API_KEY: cdc2313d-b0ae-b48e-4e2b-143fb7ad258e:fx
            DB_HOST: legal-db
            DB_NAME: fisconet
            DB_PORT: 3005
            DB_USER: root
            DB_PASSWORD: clerypassword

    # # legal-db2:
    # #     image: couchdb:latest
    # #     volumes:
    # #         [
    # #             './legal_db/data:/opt/couchdb/data',
    # #             './legal_db/local.ini:/opt/couchdb/etc/local.ini',
    # #         ]
    # #     ports: ['5984:5984']
    # #     restart: always

    # file database
    legal-db:
        image: mongo:3
        command: mongod --port 3005
        restart: always
        volumes:
            [
                './legal_db/mongo-data:/data/db',
                './legal_db/init-db.js:/docker-entrypoint-initdb.d/init-mongo.js',
            ]
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: clerypassword
            MONGO_INITDB_DATABASE: fisconet

    # legal-viewer:
    #     image: mongo-express
    #     restart: always
    #     ports: ['8082:8081']
    #     depends_on: ['legal-db']
    #     environment:
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: clerypassword
    #         ME_CONFIG_BASICAUTH_USERNAME: root
    #         ME_CONFIG_BASICAUTH_PASSWORD: clerypassword
    #         ME_CONFIG_MONGODB_SERVER: legal-db
