
CREATE TABLE companies (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	company_name VARCHAR(255) NOT NULL UNIQUE
);


CREATE TABLE users (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	company_id INT NOT NULL,
	is_owner BOOLEAN NOT NULL,
	date_inscription DATE NOT NULL,
	FOREIGN KEY (company_id) REFERENCES companies(id)
);
